#!/bin/bash

# Utility script to set up the raw BitBake environment for PetaLinux
# IMPORTANT: This script MUST be sourced, not executed.
# Usage: source scripts/yoctoenv.sh

# 1. Find PetaLinux root (contains project-spec) using absolute path
ROOT="$(pwd -P)"
while [ ! -d "$ROOT/project-spec" ] && [ "$ROOT" != "/" ]; do
    ROOT="$(dirname "$ROOT")"
done

if [ "$ROOT" = "/" ]; then
    echo "ERROR: Not in a PetaLinux project."
    return 1 2>/dev/null || exit 1
fi

export PROOT="$ROOT"
echo "PROOT=$PROOT"

echo "Setting up BitBake environment for project: $PROOT"

# 2. Run unset LD_LIBRARY_PATH as required
unset LD_LIBRARY_PATH
echo "  [x] Unset LD_LIBRARY_PATH"

# 3. Source the Yocto e-SDK
# Using a wildcard or checking for the specific architecture script
SDK_SCRIPT="$PROOT/components/yocto/environment-setup-aarch64-xilinx-linux"
# Some PetaLinux versions use cortexa72-cortexa53, checking both common ones:
if [ ! -f "$SDK_SCRIPT" ]; then
    SDK_SCRIPT="$PROOT/components/yocto/environment-setup-cortexa72-cortexa53-xilinx-linux"
fi

if [ -f "$SDK_SCRIPT" ]; then
    source "$SDK_SCRIPT"
    echo "  [x] Sourced Yocto e-SDK ($SDK_SCRIPT)"
else
    echo "WARNING: Yocto e-SDK script not found. Expected it at $PROOT/components/yocto/"
    echo "You may need to run 'petalinux-config' once to generate the yocto components."
fi

# 4. Parse the PetaLinux variable to recipes
export BB_ENV_PASSTHROUGH_ADDITIONS="$BB_ENV_PASSTHROUGH_ADDITIONS PETALINUX PROOT"
echo "  [x] Exported PROOT and BB_ENV_PASSTHROUGH_ADDITIONS"

# 5. Source the environment setup script to be redirected to the build directory
OE_INIT_SCRIPT="$PROOT/components/yocto/layers/poky/oe-init-build-env"
if [ -f "$OE_INIT_SCRIPT" ]; then
    echo "  [x] Entering Yocto build environment..."
    source "$OE_INIT_SCRIPT"
else
    echo "ERROR: oe-init-build-env not found at $OE_INIT_SCRIPT"
    return 1 2>/dev/null || exit 1
fi

echo ""
echo "====================================================================="
echo "SUCCESS: BitBake environment is now active!"
echo ""
echo "You are now in the Yocto build directory: $(pwd)"
echo "You can now run raw bitbake commands, e.g.:"
echo "  bitbake fsbl-firmware"
echo "  bitbake virtual/kernel -c menuconfig"
echo "  bitbake -e fsbl-firmware | grep ^SRC_URI="
echo ""
echo "NOTE: Images generated by raw bitbake are placed in:"
echo "  tmp/deploy/images/<machine-name>/"
echo "You must manually copy them to \$PROOT/images/linux/ if you want"
echo "to use them with standard PetaLinux commands later."
echo "====================================================================="
